language: node_js
node_js:
  - "0.10.25"
env:
  - NODE_ENV=travis
before_install:
  - sudo npm install bower -g
  - sudo bower install
  - sudo chown -R $(whoami) /home/shippable/.npm
after_success:
  - git push git@heroku.com:frozen-tundra-7264.git